site_name: JACoW Invincible Paper Crawler
site_description: Intelligent academic paper crawler for JACoW conferences
site_author: Ming Liu
site_url: https://iuming.github.io/jacow_papers_crawler/

docs_dir: docs

theme:
  name: material
  palette:
    primary: blue
    accent: light-blue
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - search.highlight

plugins:
  - search
  - mermaid2

nav:
  - Home: index.md
  - Documentation:
    - Installation: installation.md
    - Usage Guide: usage.md
    - Individual Papers: Individual_Paper_Download_Guide.md
    - Conference Download: Conference_Download_Guide.md
    - Testing Guide: Conference_Download_Testing_Guide.md
    - Configuration: configuration.md
    - Project Summary: PROJECT_SUMMARY.md
    - Recommended Usage: Recommended_Usage_Guide.md
  - Project Info:
    - Contributing: CONTRIBUTING.md
    - Changelog: CHANGELOG.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - codehilite:
      use_pygments: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
